# =======================================================================================================================================================================
# Bonsai CI Infrastructure
# =======================================================================================================================================================================
# When updating this workflow, be mindful that the `latest` tag of must successfully build under this workflow too in order to determine which packages have changed.
name: Bonsai
on:
  push:
    # This prevents tag pushes from triggering this workflow
    branches: ['*']
  pull_request:
  workflow_dispatch:
      version:
        description: "Version"
        default: ""
      will_publish_packages:
        description: "Publish packages?"
        default: "false"
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  ContinuousIntegrationBuild: true
jobs:
  # =====================================================================================================================================================================
  # Determine build matrix
  # =====================================================================================================================================================================
  # Some of the build matrix targets are conditional, and `jobs.<job_id>.if` is evaluated before `jobs.<job_id>.strategy.matrix`
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
  # As such we build the matrix programmatically in its own job and feed it into `build-and-test`.
  create-build-matrix:
    name: Create Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.create-matrix.outputs.matrix}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create build matrix
        id: create-matrix
        run: python .github/workflows/create-build-matrix.py

  # =====================================================================================================================================================================
  # Build, test, and package
  # =====================================================================================================================================================================
  build-and-test:
    needs: create-build-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.create-build-matrix.outputs.matrix)}}
    name: ${{matrix.platform.name}} ${{matrix.configuration}}
    runs-on: ${{matrix.platform.os}}
    env:
      #TODO: Move to build configuration script
      IsReferenceDummyBuild: ${{matrix.dummy-build}}
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{matrix.checkout-ref}}

      # ----------------------------------------------------------------------- Setup tools
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Legacy .NET command line tools are only used for building the installer
      - name: Setup MSBuild command line
        if: matrix.create-installer
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet command line
        if: matrix.create-installer
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: 6.x

      # ----------------------------------------------------------------------- Configure build
      - name: Configure build
        run: python .github/workflows/configure-build.py
        env:
          github_event_name: ${{github.event_name}}
          github_ref: ${{github.ref}}
          github_run_number: ${{github.run_number}}
          release_version: ${{github.event.release.tag_name}}
          workflow_dispatch_version: ${{github.event.inputs.version}}
          workflow_dispatch_will_publish_packages: ${{github.event.inputs.will_publish_packages}}
   
      # ----------------------------------------------------------------------- Build
      - name: Restore
        run: dotnet restore Bonsai.sln

      - name: Build
        run: dotnet build Bonsai.sln --no-restore --configuration ${{matrix.configuration}}

      - name: Pack
        id: pack
        if: matrix.create-packages #TODO: Should we just pack every platform since it's important to Bonsai?
        run: dotnet pack Bonsai.sln --no-restore --no-build --configuration ${{matrix.configuration}}

      # ----------------------------------------------------------------------- Test
      - name: Test
        run: dotnet test Bonsai.sln --no-restore --no-build --configuration ${{matrix.configuration}} --verbosity normal

      # ----------------------------------------------------------------------- Repack bootstrapper
      - name: Repack bootstrapper
        if: matrix.create-installer
        run: dotnet build Bonsai --no-restore --configuration ${{matrix.configuration}} -t:Repack

      # ----------------------------------------------------------------------- Create portable zip
      - name: Create portable zip
        id: create-portable-zip
        if: matrix.create-installer
        run: python .github/workflows/create-portable-zip.py artifacts/Bonsai.zip ${{matrix.configuration}}

      # ----------------------------------------------------------------------- Build Visual Studio templates
      - name: Build Visual Studio templates
        if: matrix.create-installer
        run: msbuild /nologo /maxCpuCount Bonsai.Templates/Bonsai.Templates.sln /p:Configuration=${{matrix.configuration}} /p:DeployExtension=false

      # ----------------------------------------------------------------------- Build setup
      - name: Restore setup
        if: matrix.create-installer
        # Restoring the packages.config directly means we don't rely on the system-wide Wix install
        run: |
          nuget restore Bonsai.Setup/packages.config -SolutionDir .
          nuget restore Bonsai.Setup.Bootstrapper/packages.config -SolutionDir .

      - name: Build Setup
        id: create-installer
        if: matrix.create-installer
        run: msbuild /nologo /maxCpuCount Bonsai.Setup.sln /p:Configuration=${{matrix.configuration}}
      
      # ----------------------------------------------------------------------- Collect artifacts
      - name: Collect NuGet packages
        uses: actions/upload-artifact@v4
        if: steps.pack.outcome == 'success' && always()
        with:
          name: Packages${{matrix.artifacts-suffix}}
          if-no-files-found: error
          path: artifacts/package/${{matrix.configuration-lower}}/**

      - name: Collect portable zip
        uses: actions/upload-artifact@v4
        if: steps.create-portable-zip.outcome == 'success' && always()
        with:
          name: PortableZip${{matrix.artifacts-suffix}}
          if-no-files-found: error
          path: artifacts/Bonsai.zip

      - name: Collect installer
        uses: actions/upload-artifact@v4
        if: steps.create-installer.outcome == 'success' && always()
        with:
          name: Installer${{matrix.artifacts-suffix}}
          if-no-files-found: error
          path: artifacts/bin/Bonsai.Setup.Bootstrapper/${{matrix.configuration-lower}}-x86/**

  # =====================================================================================================================================================================
  # Determine which packages need to be published
  # =====================================================================================================================================================================
  determine-changed-packages:
    name: Detect changed packages
    runs-on: ubuntu-latest
    # We technically only need the dummy build jobs, but GitHub Actions lacks the ability to depend on specific jobs in a matrix
    needs: build-and-test
    if: github.event_name != 'pull_request'
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------------------------------------------------- Setup tools
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ----------------------------------------------------------------------- Download packages for comparison
      - name: Download packages for comparison
        uses: actions/download-artifact@v4
        with:
          pattern: Packages*
          path: artifacts

      # ----------------------------------------------------------------------- Compare packages
      - name: Compare packages
        id: compare-packages
        run: python .github/workflows/compare-nuget-packages.py artifacts/Packages-dummy-prev/ artifacts/Packages-dummy-next/ artifacts/Packages/ artifacts/ReleaseManifest

      # ----------------------------------------------------------------------- Collect release manifest
      - name: Collect release manifest
        uses: actions/upload-artifact@v4
        if: steps.compare-packages.outcome != 'skipped' && always()
        with:
          name: ReleaseManifest
          if-no-files-found: error
          path: artifacts/ReleaseManifest

  # =====================================================================================================================================================================
  # Publish to GitHub
  # =====================================================================================================================================================================
  publish-github:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    needs: [build-and-test, determine-changed-packages]
    # Pushes always publish CI packages (configure-build.py will add the branch name to the version string for branches besides main)
    # Published releases always publish packages
    # A manual workflow only publishes packages if explicitly enabled
    if: github.event_name == 'push' || github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.will_publish_packages == 'true')
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          sparse-checkout-cone-mode: false

      # ----------------------------------------------------------------------- Setup tools
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ----------------------------------------------------------------------- Download artifacts
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: Packages

      - name: Download release manifest
        uses: actions/download-artifact@v4
        with:
          name: ReleaseManifest

      - name: Download portable zip
        uses: actions/download-artifact@v4
        if: github.event_name == 'release'
        with:
          name: PortableZip

      - name: Download installer
        uses: actions/download-artifact@v4
        if: github.event_name == 'release'
        with:
          name: Installer

      - name: TEMP-LS
        run: ls -laR

      # ----------------------------------------------------------------------- Filter NuGet packages
      - name: Filter NuGet packages
        run: python .github/workflows/filter-release-packages.py ReleaseManifest Packages

      - name: TEMP-LS
        run: ls -la Packages

      # ----------------------------------------------------------------------- Upload release assets
      # ----------------------------------------------------------------------- Push to GitHub Packages

  # =====================================================================================================================================================================
  # Publish NuGet Packages to NuGet.org
  # =====================================================================================================================================================================
  publish-packages-nuget-org:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    needs: [build-and-test, determine-changed-packages]
    environment: NuGet.org
    # Release builds always publish packages to NuGet.org
    # Workflow dispatch builds will only publish packages if enabled and an explicit version number is given
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.will_publish_packages == 'true' && github.event.inputs.version != '')
    steps:
      #TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO
      - name: NOT IMPLEMENTED
        run: echo "TODO"

  # =====================================================================================================================================================================
  # Bump `latest` tag
  # =====================================================================================================================================================================
  bump-latest:
    name: Bump Latest Version Tag
    runs-on: ubuntu-latest
    # It's important that this only happens when everything else happened successfully
    # Otherwise it's possible for a partial release to occur and re-running the job wouldn't be possible due to the latest tag having already moved
    # (This is also why this happens as its own job, it lets us ensure both publish paths happened successfully.)
    needs: [publish-github, publish-packages-nuget-org]
    # Only bump latest tag when doing a full release
    if: github.event_name == 'release'
    steps:
      #TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO ðŸ§¶ TODO
      #TODO: DO NOT DO THIS WHEN IT'S A PREVIEW VERSION
      - name: NOT IMPLEMENTED
        run: echo "TODO"
      #TODO: Dispatch update to docs repo
      #TODO: Bump version number in local props file?
      #TODO: git push --force origin c6e5ecc7d2133c3fabf7e03253969bcad0379fe7:refs/tags/latest
      #TODO: Maybe make it an annotated tag instead? GitHub will show the tag's annotation rather than the associate commit message
      #      Slightly more tedious to update though
